# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='hability',
            new_name='ability',
        ),
    ]
